USE [master]
GO

CREATE DATABASE [tuServicio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tuServicio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\tuServicio.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tuServicio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\tuServicio_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tuServicio] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tuServicio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tuServicio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tuServicio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tuServicio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tuServicio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tuServicio] SET ARITHABORT OFF 
GO

ALTER DATABASE [tuServicio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tuServicio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tuServicio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tuServicio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tuServicio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tuServicio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tuServicio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tuServicio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tuServicio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tuServicio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tuServicio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tuServicio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tuServicio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tuServicio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tuServicio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tuServicio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tuServicio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tuServicio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tuServicio] SET  MULTI_USER 
GO

ALTER DATABASE [tuServicio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tuServicio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tuServicio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tuServicio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tuServicio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tuServicio] SET  READ_WRITE 
GO


